"IF"                   = r"if"
"ELSE"                 = r"else"
"WHILE"                = r"while"
"FOR"                  = r"for"

"INTEGER"              = r"int"
"DOUBLE"               = r"double"
"FLOAT"                = r"float"
"PLUS"                 = r"\+"
"MINUS"                = r"\-"
"MULTIPLY"             = r"\*"
"DIVIDE"               = r"\/"

"IDENTIFIER"           = r"[a-zA-Z]([a-zA-Z0-9])*"

"COMPARISON_OPERATOR"  = r"=="
"NOT_EQUAL"            = r"!="
"LESSER_THAN"          = r"<"
"GREATER_THAN"         = r">"
"LESSER_THAN_EQUAL"    = r"<="
"GREATER_THAN_EQUAL"   = r">="
"STATEMENT_TERMINATOR" = r";"

"PARENTHESIS_OPEN"     = r"\("
"PARENTHESIS_CLOSE"    = r"\)"
"BRACKET_OPEN"         = r"{"
"BRACKET_CLOSE"        = r"}"
"EQUAL"                = r"="

"INTEGER_LITERAL"     = r"(-?[0-9]+)"
"DOUBLE_LITERAL"       = r"(-?(([0-9]+\.[0-9]+)d|([0-9]+)d))"
"FLOAT_LITERAL"        = r"(-?(([0-9]+\.[0-9]+)f?|([0-9]+)f))"
"STRING_LITERAL"       = r"\"[a-zA-Z0-9]*\""